# Generated by Django 4.0.1 on 2022-02-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_delete_profilepic_adduser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='adduser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/images'),
        ),
    ]
