# Generated by Django 4.0 on 2022-02-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_status_alter_adduser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20)),
                ('station_name', models.CharField(max_length=20)),
                ('add_line1', models.CharField(max_length=50)),
                ('add_line2', models.CharField(max_length=30)),
            ],
        ),
    ]
